# Generated by Django 3.0.6 on 2020-06-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sstock',
            old_name='Upside',
            new_name='upside',
        ),
    ]
