# Generated by Django 2.2 on 2019-04-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='isin',
            field=models.IntegerField(default=0),
        ),
    ]
