# Generated by Django 3.0.6 on 2020-06-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200610_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='sstock',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
