# Generated by Django 2.2 on 2019-04-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_stock_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='isin',
            field=models.CharField(max_length=200),
        ),
    ]
