# Generated by Django 3.0.6 on 2020-06-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_sstock_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sstock',
            old_name='net_Cash',
            new_name='net_cash',
        ),
    ]
