# Generated by Django 3.0.6 on 2020-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200612_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sstock',
            name='completion_date',
            field=models.DateField(),
        ),
    ]
