# Generated by Django 2.2 on 2019-04-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190418_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
