# Generated by Django 2.2 on 2019-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_histr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histr',
            name='id',
        ),
        migrations.AlterField(
            model_name='histr',
            name='isin',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
