# Generated by Django 2.2 on 2019-06-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20190419_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='sStock',
            fields=[
                ('ISIN', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('markCap', models.CharField(max_length=200)),
                ('divCap', models.CharField(max_length=200)),
                ('divCapZero', models.CharField(max_length=200)),
                ('divCapOne', models.CharField(max_length=200)),
                ('divCapTwo', models.CharField(max_length=200)),
                ('divCapThird', models.CharField(max_length=200)),
                ('divCapFour', models.CharField(max_length=200)),
                ('divCapFive', models.CharField(max_length=200)),
                ('divCapSix', models.CharField(max_length=200)),
                ('resCap', models.CharField(max_length=200)),
                ('ownZero', models.CharField(max_length=200)),
                ('ownOne', models.CharField(max_length=200)),
                ('ownTwo', models.CharField(max_length=200)),
                ('ownThree', models.CharField(max_length=200)),
                ('ownFour', models.CharField(max_length=200)),
                ('ownFive', models.CharField(max_length=200)),
                ('ownSix', models.CharField(max_length=200)),
                ('forCap', models.CharField(max_length=200)),
                ('forZero', models.CharField(max_length=200)),
                ('forOne', models.CharField(max_length=200)),
                ('forThree', models.CharField(max_length=200)),
                ('forFour', models.CharField(max_length=200)),
                ('forFive', models.CharField(max_length=200)),
                ('forSix', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
